services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env.docker.example
    environment:
      RUN_MIGRATIONS: "true"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media:/app/media
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: celery -A config worker -l info
    env_file:
      - .env.docker.example
    volumes:
      - .:/app
      - media:/app/media
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: tiny_anthems
      POSTGRES_USER: tiny_anthems
      POSTGRES_PASSWORD: tiny_anthems
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres-data:
  media:
