# Generated by Django 5.2.14 on 2026-05-07 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('songs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='elevenlabs', max_length=40)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='queued', max_length=30)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('provider_request_id', models.CharField(blank=True, max_length=255)),
                ('provider_response_metadata', models.JSONField(blank=True, default=dict)),
                ('provider_cost_units', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('prompt', models.TextField(blank=True)),
                ('negative_prompt', models.TextField(blank=True)),
                ('raw_audio_file', models.FileField(blank=True, upload_to='raw-audio/')),
                ('processed_audio_file', models.FileField(blank=True, upload_to='processed-audio/')),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('song_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='songs.songrequest')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
