# Generated by Django 5.2.14 on 2026-05-07 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SongRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_payment', 'Awaiting Payment'), ('queued', 'Queued'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='draft', max_length=30)),
                ('occasion', models.CharField(choices=[('birthday', 'Birthday'), ('congratulations', 'Congratulations'), ('graduation', 'Graduation'), ('promotion', 'Promotion'), ('roast', 'Roast')], max_length=40)),
                ('recipient_name', models.CharField(max_length=80)),
                ('recipient_nickname', models.CharField(blank=True, max_length=80)),
                ('milestone', models.CharField(blank=True, max_length=80)),
                ('relationship', models.CharField(choices=[('friend', 'Friend'), ('partner', 'Partner'), ('child', 'Child'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('coworker', 'Coworker'), ('boss', 'Boss'), ('teammate', 'Teammate'), ('other', 'Other')], max_length=40)),
                ('personal_details', models.TextField()),
                ('things_to_avoid', models.TextField(blank=True)),
                ('family_friendly', models.BooleanField(default=True)),
                ('tone', models.CharField(choices=[('funny', 'Funny'), ('sweet', 'Sweet'), ('light_roast', 'Light Roast'), ('wholesome', 'Wholesome'), ('party_energy', 'Party Energy')], max_length=40)),
                ('vibe', models.CharField(choices=[('pop_anthem', 'Pop Anthem'), ('funky_groove', 'Funky Groove'), ('country_singalong', 'Country Singalong'), ('acoustic_sweet', 'Acoustic Sweet'), ('club_banger', 'Club Banger')], max_length=40)),
                ('requested_duration_seconds', models.PositiveSmallIntegerField(default=15)),
                ('generated_title', models.CharField(blank=True, max_length=160)),
                ('lyrics_preview', models.TextField(blank=True)),
                ('prompt_used', models.TextField(blank=True)),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('blocked', 'Blocked'), ('needs_review', 'Needs Review')], default='pending', max_length=30)),
                ('access_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('song_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='songs.songrequest')),
            ],
        ),
    ]
