# Generated by Django 5.2.14 on 2026-05-07 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generation', '0001_initial'),
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('raw_audio', 'Raw Audio'), ('final_mp3', 'Final MP3'), ('waveform_json', 'Waveform JSON'), ('cover_image', 'Cover Image'), ('video_card', 'Video Card')], max_length=40)),
                ('storage_key', models.CharField(max_length=500)),
                ('public_url', models.URLField(blank=True)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generation_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generation.generationjob')),
                ('song_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='songs.songrequest')),
            ],
        ),
    ]
